# Generated by Django 4.0.3 on 2022-06-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_biometric_app', '0002_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
