# Generated by Django 4.0.3 on 2022-06-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_biometric_app', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='face_biometric_app/upload')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
