# Generated by Django 4.0.3 on 2022-06-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_biometric_app', '0004_upload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fnd_detected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('photo', models.ImageField(default='test_app/facerec/detected/noimg.png', upload_to='test_app/facerec/fnd')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face_biometric_app.employee')),
            ],
        ),
    ]
