# Generated by Django 4.0.3 on 2022-06-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_biometric_app', '0005_fnd_detected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fnd_detected',
        ),
    ]
