# Generated by Django 4.0.3 on 2022-06-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_biometric_app', '0006_delete_fnd_detected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='face_biometric_app/proof')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
